const menuButton=document.querySelector('.menu-toggle');
const navigation=document.querySelector('.nav-links');
if(menuButton&&navigation){menuButton.addEventListener('click',()=>{const open=navigation.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navigation.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}))}
const yearTarget=document.getElementById('current-year');if(yearTarget)yearTarget.textContent=new Date().getFullYear();
const SUPABASE={url:'https://bldmkfdgdqlhpxgpvhmf.supabase.co',publishableKey:'sb_publishable_PLRXhKoZ2DoRpSsRWHn3vg_LCf6TYiT'};
async function callCounterRpc(functionName,body={}){const response=await fetch(`${SUPABASE.url}/rest/v1/rpc/${functionName}`,{method:'POST',headers:{apikey:SUPABASE.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});if(!response.ok)throw new Error(`contador HTTP ${response.status}`);return response.json()}
const siteVisitsTotal=document.getElementById('site-visits-total');const siteVisitsToday=document.getElementById('site-visits-today');const VISIT_KEY='jr_site_visit_registered_day';
function browserDayKey(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`}
async function loadSiteVisitStats(){if(!siteVisitsTotal||!siteVisitsToday)return;const day=browserDayKey();let previous='';try{previous=localStorage.getItem(VISIT_KEY)||''}catch{}const register=previous!==day;try{const stats=await callCounterRpc(register?'register_jr_site_visit':'get_jr_site_visit_stats');const total=Number(stats?.total);const today=Number(stats?.today);siteVisitsTotal.textContent=Number.isFinite(total)?total.toLocaleString('pt-BR'):'—';siteVisitsToday.textContent=Number.isFinite(today)?today.toLocaleString('pt-BR'):'—';if(register){try{localStorage.setItem(VISIT_KEY,day)}catch{}}}catch(error){siteVisitsTotal.textContent='—';siteVisitsToday.textContent='—';console.warn('Contador de visitas indisponível:',error)}}
loadSiteVisitStats();
