-- J.R FINANCE - CONTADOR DE DOWNLOADS DO INSTALADOR
-- Registra somente downloads liberados por uma compra aprovada.
-- O navegador pode consultar apenas o total agregado.

create table if not exists public.jr_finance_downloads (
  id bigint generated by default as identity primary key,
  checkout_session_id uuid not null references public.jr_finance_checkout_sessions(id) on delete cascade,
  version text,
  downloaded_at timestamptz not null default now()
);

alter table public.jr_finance_downloads enable row level security;
revoke all on table public.jr_finance_downloads from public, anon, authenticated;

create index if not exists jr_finance_downloads_downloaded_at_idx
  on public.jr_finance_downloads (downloaded_at desc);

create or replace function public.get_jr_finance_download_count()
returns bigint
language sql
security definer
set search_path = ''
as $$
  select count(*)::bigint from public.jr_finance_downloads;
$$;

revoke execute on function public.get_jr_finance_download_count() from public, anon, authenticated;
grant execute on function public.get_jr_finance_download_count() to anon, authenticated;

notify pgrst, 'reload schema';
